service: sls-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-bundle

custom:
  bundle:
    linting: false
    esbuild: true
    packager: 'pnpm'

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
